name: ai_agent
description: "AI Agent"
version: 1.0.0-beta.1+1
publish_to: 'none'                                      # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.8.1

# To upgrade your package dependencies to the latest versions run `flutter pub upgrade --major-versions`. Alternatively,
# To see which dependencies have newer versions available, run `flutter pub outdated`.

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Firebase core dependencies
  firebase_core_platform_interface: ^6.0.0
  firebase_core_web: ^3.1.0
  
  # Firebase auth dependencies
  firebase_auth_web: ^6.0.2
  firebase_auth_platform_interface: ^8.1.1
  
  # Other Firebase services

  # Keep other existing dependencies unchanged
  speech_to_text: ^7.3.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  jwt_decoder: ^2.0.1
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  connectivity_plus: ^7.0.0
  http: ^1.4.0
  audioplayers: ^6.5.0 
  record: ^6.0.0
  path_provider: ^2.1.5
  cached_network_image: ^3.3.1
  flutter_web_plugins:
    sdk: flutter
  shared_preferences: ^2.5.3
  change_app_package_name: ^1.5.0
  firebase_core: 4.1.0
  firebase_analytics: 12.0.1
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mockito: ^5.5.0


# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
     - assets/images/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          weight: 800
          style: italic 
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
          weight: 100            
          style: italic
    - family: Avenir
      fonts:
        - asset: assets/fonts/avenir-light.ttf
          weight: 300
        - asset: assets/fonts/avenir-regular.ttf
        - asset: assets/fonts/avenir-black.ttf
          weight: 900


  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
